apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote
spec:
  replicas: 2
  selector:
    matchLabels:
      app: vote
  template:
    metadata:
      labels:
        app: vote
    spec:
      containers:
        - name: vote
          image: ${ECR_URL}/${REPO_NAME}:${BUILD_TAG}
          ports:
            - containerPort: 5000
