apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote
spec:
  replicas: 2
  selector:
    matchLabels:
      app: vote
  template:
    metadata:
      labels:
        app: vote
    spec:
      containers:
        - name: vote
          image: 654654589559.dkr.ecr.ap-south-1.amazonaws.com/pop/test:v1.154
          ports:
            - containerPort: 5000
# Updated image tag to v1.154 at 2025-07-13T08:18:24Z
# Updated image tag to v1.155 at 2025-07-13T08:19:15Z
